export const BLOG_POST_LIST_REQUEST = 'BLOG_POST_LIST_REQUEST'
export const BLOG_POST_LIST_RECIEVED = 'BLOG_POST_LIST_RECIEVED'
export const BLOG_POST_LIST_ERROR = 'BLOG_POST_LIST_ERROR'
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD'