export const BLOG_POST_LIST_REQUEST = 'BLOG_POST_LIST_REQUEST'
export const BLOG_POST_LIST_RECIEVED = 'BLOG_POST_LIST_RECIEVED'
export const BLOG_POST_LIST_ERROR = 'BLOG_POST_LIST_ERROR'
export const BLOG_POST_LIST_ADD = 'BLOG_POST_LIST_ADD'

export const BLOG_POST_REQUEST = 'BLOG_POST_REQUEST'
export const BLOG_POST_RECIEVED = 'BLOG_POST_RECIEVED'
export const BLOG_POST_ERROR = 'BLOG_POST_ERROR'
export const BLOG_POST_UNLOAD = 'BLOG_POST_UNLOAD'

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST'
export const COMMENT_LIST_RECIEVED = 'COMMENT_LIST_RECIEVED'
export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR'
export const COMMENT_LIST_UNLOAD = 'COMMENT_LIST_UNLOAD'